= APIkit for SOAP
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

APIkit for SOAP is a framework for simplifying the development and integration of SOAP-based APIs. SOAP (Simple Object Access Protocol) is a messaging protocol for exchanging structured information between web services. APIkit for SOAP capabilities in managing SOAP message formats and headers ensure seamless integration with SOAP infrastructure. With APIkit for SOAP, you can create robust and reliable SOAP-based APIs, accelerating your development workflow and delivering enhanced integration capabilities.

== APIkit for SOAP Features

* Streamlines SOAP API development, ensuring seamless integration with your existing SOAP infrastructure.
* Simplifies the handling of SOAP message formats and headers, so you can focus on the core logic of your APIs. 
* Automates the binding to WSDL (Web Services Description Language), reducing manual configuration efforts and ensuring accuracy.
* Supports data transformations.
* Defines and exposes SOAP APIs with ease by emphasizing SOAP/WSDL contracts. 

== See Also

* xref:apikit-4-soap-prerequisites-task.adoc[]
