= Supported Bindings and Parametrized Channels in APIkit for AsyncAPI 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

APIkit for AsyncAPI supports various bindings to enable message-driven architectures, and it also supports parametrized channels to define dynamic and reusable configurations.

== Supported Bindings

=== Anypoint Connector for MQ (Anypoint MQ Connector) 

[%header%autowidthspread,cols="1a,1a,1a,3a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference

|

destination

destinationType

headers

| destination
| destination
| OPTIONAL, defaults to the channel name. The destination (queue or exchange) name for this channel. SHOULD only be specified if the channel name differs from the actual destination name, such as when the channel name is not a valid destination name in Anypoint MQ.
| See https://github.com/asyncapi/bindings/blob/b1e7736071ccddc6c3d652bb2071cad4549f8a08/anypointmq/README.md[Anypoint MQ Bindings]

| headers
| N/A
| N/A
| OPTIONAL. A Schema object containing the definitions for Anypoint MQ-specific headers (so-called protocol headers). This schema MUST be of type object and have a properties key. Examples of Anypoint MQ protocol headers are messageId and messageGroupId.

----
       payload:
          type: object
          properties:
            #...
        correlationId:
          description: Correlation ID is specified as a header and transmitted in the Anypoint MQ message properties section
          location:    $message.header#/correlationId
        bindings:
          anypointmq:
            headers:
              type: object
              properties:
                messageId:
                  type: string
            bindingVersion: '0.1.0'

----
| See https://github.com/asyncapi/bindings/blob/b1e7736071ccddc6c3d652bb2071cad4549f8a08/anypointmq/README.md[Anypoint MQ bindings].

| N/A
| `destination` 
| `destination` 
| By default, Anypoint MQ Connector uses the channel name as the `destination`. You must specify the `destination` (queue or exchange) name if the channel name differs from the actual `destination` name, or if the channel name isn’t a valid `destination` name.
| See https://github.com/asyncapi/bindings/blob/b1e7736071ccddc6c3d652bb2071cad4549f8a08/anypointmq/README.md[Anypoint MQ bindings].
|===

=== Kafka Connector

[%header%autowidthspread,cols="1a,1a,1a,3a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference

| key
| key
| key
| The message key.
.7+| See https://github.com/asyncapi/bindings/blob/master/kafka/README.md[Kafka bindings].

|schemaIdLocation
| N/A
| N/A
| If a Schema Registry is used when performing this operation, tells where the id of the schema is stored (e.g. header or payload).

| schemaIdPayloadEncoding
| N/A
| N/A
| Number of bytes or vendor-specific values when schema id is encoded in the payload (e.g confluent/ apicurio-legacy / apicurio-new).

| schemaLookupStrategy
| N/A
| N/A
|Freeform string for any naming strategy class to use. Clients should default to the vendor default if not supplied.

[source,xml,linenums]
----
channels:
  test:
    address: test-topic
    messages:
      testMessage:
        bindings:
          kafka:
            key:
              type: string
              enum: ['myKey']
            schemaIdLocation: 'payload'
            schemaIdPayloadEncoding: 'apicurio-new'
            schemaLookupStrategy: 'TopicIdStrategy'
            bindingVersion: '0.5.0'
----
| 

schemaRegistryVendor

Topic

Partitions

Replicas

| N/A
| N/A
|  
[source,xml,linenums]
----
user-signedup:
    bindings:
      kafka:
        topic: 'my-specific-topic-name'
        partitions: 20
        replicas: 3
        topicConfiguration:
          cleanup.policy: ["delete", "compact"]
          retention.ms: 604800000
          retention.bytes: 1000000000
          delete.retention.ms: 86400000
          max.message.bytes: 1048588
        bindingVersion: '0.5.0'
----

| topicConfiguration
| N/A
| N/A
|
[source,xml,linenums]
----
topicConfiguration:
  cleanup.policy: ["delete", "compact"]
  retention.ms: 604800000
  retention.bytes: 1000000000
  delete.retention.ms: 86400000
  max.message.bytes: 1048588
  confluent.key.schema.validation: true
  confluent.key.subject.name.strategy: "TopicNameStrategy"
  confluent.value.schema.validation: true
  confluent.value.subject.name.strategy: "TopicNameStrategy"
----

| 

groupId

clientId
| N/A
| N/A
| 
[source,xml,linenums]
----
channels:
  user-signedup:
operations:
  userSignup:
    action: receive
    bindings:
      kafka:
        groupId:
          type: string
          enum: ['myGroupId']
        clientId:
          type: string
          enum: ['myClientId']
        bindingVersion: '0.5.0'
----
|===

=== Solace

[%header%autowidthspread,cols="1a,1a,1a,3a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference
|
|
|
|
|
|===

=== Solace PubSub+ Connector

[%header%autowidthspread,cols="1a,1a,1a,3a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference
| 
| `deliveryMode` 
| `deliveryMode` 
| Solace PubSub+ Connector operates in `direct` or `persistent` mode. The default mode is `persistent`. The `deliveryMode` parameter determines the quality of service for publishing messages. The `Direct` mode offers lower latency but doesn’t guarantee message delivery. The ‘persistent’ mode ensures that messages are reliably delivered, even in the event of a broker failure.
.3+| See https://github.com/asyncapi/bindings/blob/master/solace/README.md[Solace bindings].

|
| `destinationType` 
| `destinationType` 
| Solace PubSub+ Connector supports `queue` in APIkit for AsyncAPI. 

|
| N/A 
| `topicSubscriptions` 
| Solace PubSub+ Connector specifies the list of topics the queue subscribes to when the `destinationType` is `queue`. If you specify no topic, the `queue` automatically subscribes to the topic the channel name represents. 

|===

[NOTE]
Anypoint Connector for Apache Kafka (Apache Kafka Connector) and Solace PubSub+ Connector don’t support bindings.

== Parameterized Channels

APIkit for AsyncAPI supports parametrized channels so you can define dynamic and reusable configurations, scale your integrations more effectively, and create consistent configurations across different parts of the integration.

APIkit for AsyncAPI doesn't support parameters if they're defined in a binding. For example, a `destination` in AnypointMQ.

The following code provides a partial API spec example with a parameterized `destination`: 

[source,yaml,linenums]
----
channels:
  orderAcknowledgement:
    description: new Order Acknowledgment
    servers: 
      - anypointMQ
    bindings:
      anypointmq:
        destination: '{env}.amq-asyncapi-poc.orderAcknowledgement'
        destinationType: queue
    parameters:
      env: 
        $ref: '#/components/parameters/env'
    publish:
      operationId: listen-order-ack
      description: publish a new Order Acknowledgment event to this channel and we will process it
      message:
        $ref: '#/components/messages/orderAckMessage'
----

You must set the parametrized channel at design time. You can't set the parametrized channel at runtime. 

See the complete API example using parametrized channels:

----
asyncapi: '2.6.0'
info:
  title: AMQ-AsyncAPI-PoC
  version: '1.0.11'
  description: Proof of Concept for Anypoint MQ AsyncAPI interface
  contact:
    name: Example Company
    email: address@example.com
tags:
  - name: WMS
    description: Warehouse Management System
  - name: PoC
    description: Proof of Concept
  - name: Order Acknowledgement

servers:
  anypointMQ:
    url: https://{region}.anypoint.mulesoft.com/api/{version}/organizations/{organizationId}/environments/{environmentId}
    protocol: anypointmq
    protocolVersion: v1
    description: The Anypoint MQ broker
    variables:
      region:
        $ref: '#/components/serverVariables/region'
      version:
        $ref: '#/components/serverVariables/version'
      organizationId:
        $ref: '#/components/serverVariables/organizationId'
      environmentId:
        $ref: '#/components/serverVariables/environmentId'

channels:
  orderAcknowledgement:
    description: new Order Acknowledgment
    servers: 
      - anypointMQ
    bindings:
      anypointmq:
        destination: '{env}.amq-asyncapi-poc.orderAcknowledgement'
        destinationType: queue
    parameters:
      env: 
        $ref: '#/components/parameters/env'
    publish:
      operationId: listen-order-ack
      description: publish a new Order Acknowledgment event to this channel and we will process it
      message:
        $ref: '#/components/messages/orderAckMessage'

components:
  parameters:
    env:
      description: The Mule runtime environment 
      schema:
        type: string
        enum:
          - dev
          - tst
          - acc
          - prd
        default: tst
  serverVariables:
    region:
      description: The CloudHub region where the endpoint is situated
      enum:
        - mq-eu-west-1
      default: mq-eu-west-1
    version:
      description: The version of the Anypoint MQ API
      enum:
        - v1
      default: v1
    organizationId:
      description: The identifier of our organization (business group)
      enum:
        - 7a2b1c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5p
    environmentId:
      description: The identifier of the runtime environment within the organization
      enum:
        - a1b2c3d4-5e6f-7g8h-9i0j-1k2l3m4n5o6p
        - b2c3d4e5-6f7g-8h9i-0j1k-2l3m4n5o6p
        - c3d4e5f6-7g8h-9i0j-1k2l-3m4n5o6p
      default: a1b2c3d4-5e6f-7g8h-9i0j-1k2l3m4n5o6p
  messages:
    orderAckMessage:
      name: OrderAckMessage
      description: An order acknowledgment message.
      payload:
        $ref: 'schemas/orderAcknowledgement.json'
----

[NOTE]
APIkit for AsyncAPI uses the parametrized channels only on `listeners`. 
