= APIkit for AsyncAPI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

include::reuse::partial$beta-banner.adoc[tag="apikit-asyncapi"]

APIkit for AsyncAPI is a module that provides a valuable addition to Anypoint Platform by enabling you to xref:design-center::design-async-api.adoc[design event-driven APIs from API Designer]. You can create AsyncAPI specifications for defining APIs using asynchronous messaging protocols. 

AsyncAPI is based on event-driven architectures that communicate data between different systems reliably and efficiently.

You can quickly implement projects with the APIkit scaffolder by generating the initial skeleton of the application. Scaffold and re-scaffold your Mule application in xref:code-builder::ref-acb-commands.adoc[AnyPoint Code Builder] and xref:studio::add-modules-in-studio-to.adoc[Anypoint Studio].

[NOTE]
APIkit for AsyncAPI supports the https://www.asyncapi.com/blog/release-notes-2.6.0[AsyncAPI 2.6 spec].

== See Also

* xref:apikit-asyncapi-module-reference.adoc[]
* xref:apikit-asyncapi-error-handling-reference.adoc[]
* xref:design-center::design-async-api.adoc[]
