= Supported Bindings and Parametrized Channels in APIkit for AsyncAPI 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

APIkit for AsyncAPI supports various bindings to enable message-driven architectures, and parametrized channels to define dynamic and reusable configurations.

== Supported Bindings

=== Anypoint Connector for MQ (Anypoint MQ Connector) 

[%header%autowidthspread,cols="1a,1a,1a,1a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference

| `Destination`
| `Destination`
| `Destination`
| `Destination` (queue or exchange) name for this channel. It's optional and defaults to the channel name. Specify it if the channel name differs from the actual `destination` name. For example, if the channel name isn't a valid `destination` name in Anypoint MQ.
.2+| See https://github.com/asyncapi/bindings/blob/b1e7736071ccddc6c3d652bb2071cad4549f8a08/anypointmq/README.md[Anypoint MQ Bindings].

|`DestinationType`
|`DestinationType`
|`DestinationType`
| Type of destination (queue or exchange, or FIFO queue). It's optional and defaults to `queue`. Specifies the messaging model supported by this channel:

* Publish/subscribe
* Point-to-point
* Strict message ordering
|===

=== Kafka Connector

[%header%autowidthspread,cols="1a,1a,1a,1a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference

| `Key`
| `Key`
| `Key`
| Key associated with the message in this channel. It's optional and defaults to `no key`. Specifies if the message requires a specific key for partitioning or message grouping. 
| See https://github.com/asyncapi/bindings/blob/master/kafka/README.md[Kafka bindings].
|===

=== Solace

[%header%autowidthspread,cols="1a,1a,1a,1a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference

| N/A
| `DeliveryMode`
| `DeliveryMode`
| Quality of service for publishing messages. Values can be `Direct` or `persistent` (default).
.8+| See https://github.com/asyncapi/bindings/blob/master/solace/README.md[Solace bindings].

| N/A
| `DestinationType`
| `DestinationType`
| Type of destination for messages, such as `queue` or `topic`. Only `queue` is currently supported.

| N/A
| N/A
| `TopicSubscriptions`
| List of topics that the queue subscribes to if `destinationType` is `queue`. If none is given, the queue subscribes to the `topic` as represented by the channel name.

| `MsgVpn`
| N/A
| N/A
| VPN name on the Solace broker.

| `Destinations`
| N/A
| N/A
| Specific queues or topics where messages are sent or received.

| `timeToLive`
| N/A
| N/A
| Interval in milliseconds or a schema object containing the definition of the lifetime of the message.

| `priority`
| N/A
| N/A
| Priority level of a message. Priority value ranges from 0 to 255, where 0 is the lowest priority and 255 is the highest. A schema object containing the definition of the priority is also valid.

| `DmqEligible`
| N/A
| N/A
| Eligibility of a message to be moved to a dead-message queue (DMQ). Default value is `false`.
----
operations:
  addPerson:
    action: send
    channel:
      $ref: '#/channels/address'
    messages:
      - $ref: '#/channels/address/messages/personEvent'
    bindings:
      solace:
        bindingVersion: 0.4.0
        destinations:
          - destinationType: queue
            queue:
              name: CreatedHREvents
              topicSubscriptions:
                - person/*/created
          - destinationType: queue
            queue:
              name: UpdatedHREvents
              topicSubscriptions:
                - person/*/updated
        timeToLive: 5000
        priority: 120
        dmqEligible: true
----
|===

=== Solace PubSub+ Connector

[%header%autowidthspread,cols="1a,1a,1a,3a,1a"]
|===
| Binding | Publish | Message Listener | Description | Reference
| `deliveryMode`
| `deliveryMode` 
| `deliveryMode` 
| Solace PubSub+ Connector operates in `direct` or `persistent` mode. The default mode is `persistent`. The `deliveryMode` parameter determines the quality of service for publishing messages. The `Direct` mode offers lower latency but doesn't guarantee message delivery. The `persistent` mode ensures that messages are reliably delivered, even in the event of a broker failure.
.3+| See https://github.com/asyncapi/bindings/blob/master/solace/README.md[Solace bindings].

|
| `destinationType` 
| `destinationType` 
| Solace PubSub+ Connector supports `queue` in APIkit for AsyncAPI. 

|
| N/A 
| `topicSubscriptions` 
| Solace PubSub+ Connector specifies the list of topics the queue subscribes to when the `destinationType` is `queue`. If you specify no topic, the `queue` automatically subscribes to the topic the channel name represents. 

|===

[NOTE]
Anypoint Connector for Apache Kafka (Apache Kafka Connector) and Solace PubSub+ Connector don't support bindings.

== Parameterized Channels

APIkit for AsyncAPI supports parametrized channels so you can define dynamic and reusable configurations, scale your integrations more effectively, and create consistent configurations across different parts of the integration.

APIkit for AsyncAPI doesn't support parameters if they're defined in a binding. For example, a `destination` in AnypointMQ.

This code provides a partial API spec example with a parameterized `destination`: 

[source,yaml,linenums]
----
channels:
  orderAcknowledgement:
    description: new Order Acknowledgment
    servers: 
      - anypointMQ
    bindings:
      anypointmq:
        destination: '{env}.amq-asyncapi-poc.orderAcknowledgement'
        destinationType: queue
    parameters:
      env: 
        $ref: '#/components/parameters/env'
    publish:
      operationId: listen-order-ack
      description: publish a new Order Acknowledgment event to this channel and we will process it
      message:
        $ref: '#/components/messages/orderAckMessage'
----

You must set the parametrized channel at design time. You can't set the parametrized channel at runtime. 

See the complete API example using parametrized channels:

----
asyncapi: '2.6.0'
info:
  title: AMQ-AsyncAPI-PoC
  version: '1.0.11'
  description: Proof of Concept for Anypoint MQ AsyncAPI interface
  contact:
    name: Example Company
    email: address@example.com
tags:
  - name: WMS
    description: Warehouse Management System
  - name: PoC
    description: Proof of Concept
  - name: Order Acknowledgement

servers:
  anypointMQ:
    url: https://{region}.anypoint.mulesoft.com/api/{version}/organizations/{organizationId}/environments/{environmentId}
    protocol: anypointmq
    protocolVersion: v1
    description: The Anypoint MQ broker
    variables:
      region:
        $ref: '#/components/serverVariables/region'
      version:
        $ref: '#/components/serverVariables/version'
      organizationId:
        $ref: '#/components/serverVariables/organizationId'
      environmentId:
        $ref: '#/components/serverVariables/environmentId'

channels:
  orderAcknowledgement:
    description: new Order Acknowledgment
    servers: 
      - anypointMQ
    bindings:
      anypointmq:
        destination: '{env}.amq-asyncapi-poc.orderAcknowledgement'
        destinationType: queue
    parameters:
      env: 
        $ref: '#/components/parameters/env'
    publish:
      operationId: listen-order-ack
      description: publish a new Order Acknowledgment event to this channel and we will process it
      message:
        $ref: '#/components/messages/orderAckMessage'

components:
  parameters:
    env:
      description: The Mule runtime environment 
      schema:
        type: string
        enum:
          - dev
          - tst
          - acc
          - prd
        default: tst
  serverVariables:
    region:
      description: the CloudHub region where the endpoint is situated
      enum:
        - mq-eu-west-1
      default: mq-eu-west-1
    version:
      description: the version of the Anypoint MQ API
      enum:
        - v1
      default: v1
    organizationId:
      description: the identifier of our organization (business group)
      enum:
        - 7a2b1c3d-4e5f-6g7h-8i9j-0k1l2m3n4o5p
    environmentId:
      description: the identifier of the runtime environment within the organization
      enum:
        - a1b2c3d4-5e6f-7g8h-9i0j-1k2l3m4n5o6p
        - b2c3d4e5-6f7g-8h9i-0j1k-2l3m4n5o6p
        - c3d4e5f6-7g8h-9i0j-1k2l-3m4n5o6p
      default: a1b2c3d4-5e6f-7g8h-9i0j-1k2l3m4n5o6p
  messages:
    orderAckMessage:
      name: OrderAckMessage
      description: an order acknowledgment message.
      payload:
        $ref: 'schemas/orderAcknowledgement.json'
----

[NOTE]
APIkit for AsyncAPI uses the parametrized channels only on `listeners`. 
