= APIkit for OData V4
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

APIkit for OData v4 is a framework that simplifies the development of RESTful APIs that adhere to the OData v4 specification. OData, also called Open Data Protocol, enables the creation and consumption of RESTful APIs. It allows data querying and manipulation through standard HTTP requests.

APIkit for OData enables you to generate Mule flows that handle OData requests to create OData APIs. For example, you can expose a legacy API as an OData API, orchestrate and transform data before exposing it in Salesforce, or create a bidirectional OData API for databases such as Oracle, DB2, or Azure DB.

While the APIkit for OData v2 extension is based on RAML APIs, APIkit for OData v4 leverages the Entity Data Model (EDM) used by OData services to build HTTP-based data services. The EDM formalizes the resource descriptions and structures within the OData service. 

== See Also

* xref:apikit-4-for-odatav2.adoc[]
* xref:install-odatav4-tooling.adoc[]
