= APIkit Compatibility
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

The following table shows the compatibility between APIkit modules and the corresponding Mule versions:

[%header]
|===
|Module |Mule 3 |Mule 4
|APIkit for AsyncAPI |No |Yes 
|APIkit for gRPC |No |Yes 
|APIkit for GraphQL |No |Yes 
|APIkit for OData v2 |Yes |Yes 
|APIkit for OData v4 |No |Yes 
|APIkit for REST |Yes |Yes 
|APIkit for SOAP |Yes |Yes 
|===

Some versions of APIkit are compliant with FIPS 140-2 standards. For more information about versions of APIkit that meet these compliance standards, see the xref:apikit-release-notes.adoc[]. Additionally, learn about xref:mule-runtime::fips-140-2-compliance-support.adoc[Mule runtime FIPS 140-2 Compliance Support].

== Language and Protocol Support

[%header]
|===
| Language/protocol | Version
| AsyncAPI spec | 2.6
| Protocol Buffers (gRPC) | 3
| OData | 2.0 and 4.0
| OpenAPI Specification (OAS) | 2.0 and 3.0
| RESTful API Modeling Language (RAML) | 1.0 and 0.8
| SOAP | 1.1 and 1.2
|===

== Next Steps

Depending on the language and protocols you want to use to develop your Mule application, choose the APIkit module that best suits your needs.

* xref:apikit-for-asyncapi.adoc[]
* xref:apikit-for-grpc.adoc[]
* xref:apikit-4-for-graphql.adoc[]
* xref:apikit-4-for-odatav2.adoc[]
* xref:apikit-4-for-odatav4.adoc[]
* xref:apikit-4-for-rest.adoc[]
* xref:apikit-4-for-soap.adoc[]
