= Retrieving RAML API Files Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can retrieve the root RAML file and its included files by performing a GET request using curl or an HTTP client, such as Postman. If you are using RAML 0.8, you can resolve the root RAML file and all included files in one call. You send a Header and the URL in a GET request as follows:

* Header: *Accept: application/raml+yaml*
* URL: `{scheme}://{host}:{port}/{console path}`

*RAML 0.8 Example*

* Header: Accept: application/raml+yaml
* URL: `+http://localhost:8081/console+`

If you use RAML 1.0, you don't need to send a header. You can view the root RAML in one call using the GET method. You can also view any other included resource using the GET method as follows:

URL: `{scheme}://{host}:{port}/{console path}/{api resources folder}{optional resource path}/?raml`

*RAML 1.0 Example - View the Root RAML file*

URL: `+http://localhost:8081/console/api/?raml+`

*RAML 1.0 Example - View an Included file*

URL: `+http://localhost:8081/console/api/user.schema.json?raml+`

*RAML 1.0 Example - View a RAML Fragment*

URL: `+http://localhost:8081/console/api/types/raml-types.raml?raml+`

== See Also

* xref:retrieve-raml-task.adoc[To Retrieve RAML Files]