= Supported Bindings and Parametrized Channels in APIkit for AsyncAPI 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

APIkit for AsyncAPI supports various bindings to enable message-driven architectures.

[%header%autowidthspread]
|===

| Connector | Publish | Message Listener | Description | Reference

| AnypointMQ | `destination` | `destination` | 

The AnypointMQ connector defaults to using the channel name as the `destination`. The `destination` (queue or exchange) name for this channel must be specified if the channel name differs from the actual `destination` name or if the channel name isn’t a valid `destination` name.

| See https://github.com/asyncapi/bindings/blob/b1e7736071ccddc6c3d652bb2071cad4549f8a08/anypointmq/README.md[Anypoint MQ Bindings].

.3+| Solace

| `deliveryMode` | `deliveryMode` | The Solace connector operates in `direct` or `persistent` mode. The default mode is `persistent`. The `deliveryMode` parameter determines the quality of service for publishing messages. The `Direct` mode offers lower latency but doesn’t guarantee message delivery. The ‘persistent’ mode ensures that messages are reliably delivered, even in the event of a broker failure.

| See https://github.com/asyncapi/bindings/blob/master/solace/README.md[Solace Bindings].

| `destinationType` | `destinationType` | The Solace connector supports `queue` in APIkit for AsyncAPI. | See https://github.com/asyncapi/bindings/blob/master/solace/README.md[Solace Bindings].

| N/A | `topicSubscriptions` | The Solace connector specifies the list of topics to which the queue subscribes if the `destinationType` is `queue`. If you specify no topic, the `queue` automatically subscribes to the topic the channel name represents. | See https://github.com/asyncapi/bindings/blob/master/solace/README.md[Solace Bindings].

|===

[NOTE]
Kafka and Solace Pub/Sub connectors don’t support bindings.

== Parameterized Channels

APIkit for AsyncAPI supports parametrized channels. It doesn't support parameters if they're defined in a binding, for example: a `destination` in AnypointMQ.

The following code provides an API spec example with a parameterized `destination`: 

[source,yaml,linenums]
----
channels:
  orderAcknowledgement:
    description: new Order Acknowledgment
    servers: 
      - anypointMQ
    bindings:
      anypointmq:
        destination: '{env}.rit-amq-asyncapi-poc.orderAcknowledgement'
        destinationType: queue
    parameters:
      env: 
        $ref: '#/components/parameters/env'
    publish:
      operationId: listen-order-ack
      description: publish a new Order Acknowledgment event to this channel and we will process it
      message:
        $ref: '#/components/messages/orderAckMessage'
----

You must set the parametrized channel at design time. You can't set the parametrized channel at runtime. 

See the complete API with parametrized channels:

----
asyncapi: '2.6.0'
info:
  title: AMQ-AsyncAPI-PoC
  version: '1.0.11'
  description: Proof of Concept for Anypoint MQ AsyncAPI interface
  contact:
    name: Data Integrations team
    email: integrations@rituals.com
tags:
  - name: WMS
    description: Warehouse Management System
  - name: PoC
    description: Proof of Concept
  - name: Order Acknowledgement

servers:
  anypointMQ:
    url: https://{region}.anypoint.mulesoft.com/api/{version}/organizations/{organizationId}/environments/{environmentId}
    protocol: anypointmq
    protocolVersion: v1
    description: The Anypoint MQ broker
    variables:
      region:
        $ref: '#/components/serverVariables/region'
      version:
        $ref: '#/components/serverVariables/version'
      organizationId:
        $ref: '#/components/serverVariables/organizationId'
      environmentId:
        $ref: '#/components/serverVariables/environmentId'

channels:
  orderAcknowledgement:
    description: new Order Acknowledgment
    servers: 
      - anypointMQ
    bindings:
      anypointmq:
        destination: '{env}.rit-amq-asyncapi-poc.orderAcknowledgement'
        destinationType: queue
    parameters:
      env: 
        $ref: '#/components/parameters/env'
    publish:
      operationId: listen-order-ack
      description: publish a new Order Acknowledgment event to this channel and we will process it
      message:
        $ref: '#/components/messages/orderAckMessage'

components:
  parameters:
    env:
      description: The Mule runtime environment 
      schema:
        type: string
        enum:
          - dev
          - tst
          - acc
          - prd
        default: tst
  serverVariables:
    region:
      description: The CloudHub region where the endpoint is situated
      enum:
        - mq-eu-west-1
      default: mq-eu-west-1
    version:
      description: The version of the Anypoint MQ API
      enum:
        - v1
      default: v1
    organizationId:
      description: The identifier of our organization (business group)
      enum:
        - fbd3c996-fe4f-4194-9540-af4ba3be84ff
    environmentId:
      description: The identifier of the runtime environment within the organization
      enum:
        - 586efaf1-2f31-495f-9667-4c565b4fc5aa
        - 0af0d416-8497-4c65-adac-f951de95443e
        - 12d54a4f-9e2e-49e5-9e1f-15f4f1145bc9
      default: 586efaf1-2f31-495f-9667-4c565b4fc5aa
  messages:
    orderAckMessage:
      name: OrderAckMessage
      description: An order acknowledgment message.
      payload:
        $ref: 'schemas/orderAcknowledgement.json'
----

[NOTE]
APIkit for AsyncAPI uses the parametrized channel only on `listeners`. 
