= APIkit for REST Module Reference
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Learn the fundamentals about dependency, namespace, schema, and other information about APIkit for REST.

== APIkit for REST Dependency Information

----
<dependency>
  <groupId>org.mule.modules</groupId>
  <artifactId>mule-apikit-module</artifactId>
  <version>LATEST_VERSION</version> //<!--1-->
  <classifier>mule-plugin</classifier>
</dependency>
----
[calloutlist]
.. Check https://docs.mulesoft.com/release-notes/apikit/apikit-release-notes[APIkit release notes] to get the *LATEST_VERSION*.

== APIkit for REST Namespace and Schema

----
xmlns:apikit="http://www.mulesoft.org/schema/mule/mule-apikit"
xsi:schemaLocation="http://www.mulesoft.org/schema/mule/mule-apikit http://www.mulesoft.org/schema/mule/mule-apikit/current/mule-apikit.xsd"
----

== APIkit for REST Configuration and Operations

[%header,cols="30a,50a,8a"]
|===
|Element Name |Description |Required
|`apikit:config` |APIkit configuration |Yes
|`apikit:console` |Property of `config-ref` in the `http:listener` element in the api-console flow that defines the API console URL |No
|`apikit:router` |REST routing message processor nested in the flow element |Yes
|===

=== apikit:config Attributes

The `apikit:config` attributes are of `NonBlankString`type`.

[%header,cols="22a,10a,68a"]
|===
|Attribute Name|Required |Description
|`outboundHeadersMapName` |No |Name of the map that contains response headers.
|`httpStatusVarName` |No |Name of the variable that stores the HTTP status code in the response.
|`keepRamlBaseUri` |No |Alias for the equivalent `keepApiBaseUri` attribute.

This attribute is deprecated as of version APIkit 1.2.0. Included to provide compatibility with APIkit 1.1.x. +
Use `keepApiBaseUri` instead of `keepRamlBaseUri` in your API implementations.
| `name` |Yes |Configuration name that other elements, such as `apikit:router`, reference
| `raml` |Yes |Alias for the equivalent `api` attribute

This attribute is deprecated as of version APIkit 1.2.0. Included to provide compatibility with APIkit 1.1.x. +
Use `api` instead of `raml` in your API implementations.
| `parser` | No |Parser used to validate requests

Attribute valid for APIkit 1.2.0 and later.

Possible values are:

* AUTO
+
*APIkit Router* starts by using AMF. If it has errors, it starts by using the RAML parser.
* AMF
+
*APIkit Router* uses AMF to read the API and validate incoming requests.
* RAML
+
*APIkit Router* starts by using AMF, and if it has errors, it starts by using the RAML parser.

Default Value: AUTO.

| `api` | No | Root API file location

This attribute is valid for APIkit 1.2.0 and later.

The `api` attribute can be any URL, the relative path to a file located under `src/main/resources/api`, or the `API Sync` resource path.

| `keepApiBaseUri` | No | Attribute valid for APIkit 1.2.0 and later

When set to `false`, APIkit rewrites the `baseUri` in the RAML definition of the API. +
If set to `true`, APIkit does not rewrite the `baseUri` field.

|===

If you use APIkit behind a reverse proxy and set `keepRamlBaseUri` to `true`, use *API Console* to put the URL of a proxy in the `baseUri` property.

=== apikit:router Attributes

[%header,cols="22a,10a,68a"]
|===
|Attribute Name|Required |Description
|`disableValidations` |No | Disables validations of requests
|`headerStrictValidation` |No | Validates that request headers are defined in RAML file or belong to a well-known set of headers
|`queryParamsStrictValidation` |No | Validates that request query parameters are defined in RAML file
|===
