= APIkit Compatibility
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Compare APIkit module support on Mule 3 and Mule 4 before you choose an implementation stack. Review protocol and language coverage in the tables on this page when you plan AsyncAPI, gRPC, GraphQL, OData, REST, or SOAP APIs. For APIkit versions that align with xref:mule-runtime::fips-140-2-compliance-support.adoc[FIPS 140-2] expectations, see xref:apikit-release-notes.adoc[].

[%header]
|===
|Module |Mule 3 |Mule 4
|APIkit for AsyncAPI |No |Yes 
|APIkit for gRPC |No |Yes 
|APIkit for GraphQL |No |Yes 
|APIkit for OData v2 |Yes |Yes 
|APIkit for OData v4 |No |Yes 
|APIkit for REST |Yes |Yes 
|APIkit for SOAP |Yes |Yes
|===

== APIkit for SOAP Module Versions and Mule Runtime

APIkit for SOAP 1.7.0 provides broad Mule runtime compatibility. APIkit for SOAP 2.0.0 is the major successor to 1.6.10 and requires JDK 17 and Mule runtime 4.9.11 or later. APIkit for SOAP 1.6.5 through 1.6.10 are deprecated.

include::partial$apikit-soap-rn-version-lines-comparison.adoc[]

See xref:apikit-4-for-soap.adoc#choose-the-apikit-for-soap-module-version[Choose the APIkit for SOAP module version] and xref:apikit-4-soap-prerequisites-task.adoc[Before You Begin Using APIkit for SOAP] when you plan upgrades.

== Language and Protocol Support

[%header]
|===
| Language/protocol | Version
| AsyncAPI spec | 2.6
| Protocol Buffers (gRPC) | 3
| OData | 2.0 and 4.0
| OpenAPI Specification (OAS) | 2.0 and 3.0
| RESTful API Modeling Language (RAML) | 1.0 and 0.8
| SOAP | 1.1 and 1.2
|===

== Next Steps

Depending on the language and protocols you want to use to develop your Mule application, choose the APIkit module that best suits your needs.

* xref:apikit-for-asyncapi.adoc[]
* xref:apikit-for-grpc.adoc[]
* xref:apikit-4-for-graphql.adoc[]
* xref:apikit-4-for-odatav2.adoc[]
* xref:apikit-4-for-odatav4.adoc[]
* xref:apikit-4-for-rest.adoc[]
* xref:apikit-4-for-soap.adoc[]
