= Workflow: Creating, Testing, and Implementing an API
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords: api, raml, json

This workflow uses the free online REST service JSONPlaceholder at `+http://jsonplaceholder.typicode.com+` for example purposes.  The JSONPlaceholder service provides user information in JSON format. You design a RAML API specification and create an APIkit project in Studio based on the RAML. You simulate calls to the API, and add logic to implement the project as a Mule app. Resources are /users and /userbyid. The /users resource gets all user information. The /userbyid resource gets a particular user's information.

. Design a RAML API specification in Design Center.
+
Alternatively, you can use a text editor instead of Design Center to create the RAML specification and dependent JSON example file:
+
* xref:apikit-4-raml-text-task.adoc[Create RAML specification file].
* xref:apikit-4-json-text-task.adoc[Create a JSON example] to include in the RAML specification.
+
. xref:start-project-task.adoc[Start an APIkit project] by importing the API specification.
. xref:run-apikit-task.adoc[Run the APIkit project].
. xref:apikit-simulate.adoc[Simulate API calls to the API to test it.]
. Add business logic to the API:
+
* xref:implement-endpoint-task.adoc[Implement the endpoint] to the JsonPlaceholder service.
* xref:filter-users-id-task.adoc[Add logic to filter users by ID].
* xref:add-names-service-task.adoc[Add a service to get only names of users].
. xref:test-api-task.adoc[Test the API implementation].

== See Also

* xref:retrieve-raml-task.adoc[To Retrieve RAML Files]
* http://jsonplaceholder.typicode.com[JSONPlaceholder]
