= APIkit for AsyncAPI
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

APIkit for AsyncAPI is a module that provides a valuable addition to Anypoint Platform by enabling you to create event-driven APIs. You can create AsyncAPI specifications for defining APIs using asynchronous messaging protocols. 

AsyncAPI is based on event-driven architectures that communicate data between different systems reliably and efficiently.

The APIkit scaffolder enables you to quickly implement projects by generating the initial skeleton of the application. You can scaffold and re-scaffold your Mule application in AnyPoint Code Builder and Anypoint Studio.

[NOTE]
APIkit for AsyncAPI supports the AsyncAPI 2.6 spec.

// Note: If we consider the API lifecycle for synchronous APIs, which includes discovering, designing, implementing, managing, and monitoring, today the Anypoint Platform’s support level for event-driven APIs barely supports the implementation stage. After the October release, design and implementation are covered in ACB.

== See Also

* xref:apikit-asyncapi-module-reference.adoc[]
* xref:apikit-asyncapi-error-handling-reference.adoc[]
