= Implement the $expand Feature

The `$expand` system query option reduces the amount of incoming network traffic and makes APIs easier to consume. Because consumers request only inline representations of the related entities of query results, the returned information avoids multiple network roundtrips. This benefits metered and latency-sensitive consumers.

From APIkit for OData 1.3.0, this module supports automatic routing for ease of implementing the `$expand` system query option in the most common cases. Although this feature requires more preparation and configuration, it enables the reuse of already implemented flows when processing the `$expand` requests.

For more information on the system query option, see http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_SystemQueryOptionexpand[the OASIS specification^].

== Requirements

- APIkit for OData Module (version 1.3.0)
- A `<request-entity-collection-listener/>` implementation for each expandable entity
- Support for the `in` filter on the `<request-entity-collection-listener/>` flows

== `$expand` Feature Example 

In this example:

* The `Employee` entity has a related `Manager` entity.
* The `Employees` entity set is a collection of `Employee` entities.
* The `Managers` entity set is a collection of `Manager` entities.
* The API location is `https://example.com/api/`.

Given this setup, the following requests retrieve employees and their managers:

* Use `GET https://example.com/api/Employees` to retrieve a list of employees.
* Gather the `Manager` IDs through the `ReferentialConstraint` of their relationship.
* Use `GET https://example.com/api/Managers?$filter=ManagerID in (id1, id2, ..., idN)` to retrieve a list of related managers.
* Write a small program to merge the lists based on join criteria.

If using the `$expand` feature, requests are `GET https://example.com/api/Employees?$expand=Manager` to retrieve a list of employees with their `Manager` navigation property expanded.

== The `generic expand` Feature

The `generic expand` feature enables you to reuse existing flow implementations as a starting point for expanding requests. Using this feature, you can focus on the relevant data retrieval operations while the module performs the necessary steps to ensure that the `$expand` fields complete.

An application with the `generic expand` feature enabled works as any other OData Mule application. However, during the flow execution, once the module retrieves information for the main entity set, it performs additional internal requests gathering the information for any `expand` field. If there are errors during the expansion operation, the consumer can configure the final behavior, or the consumer can ignore it with a `null` value.

== The `generic expand` Operation

The `generic expand` feature dispatches additional queries to the application when the original flow completes. Because this is done based on the application `EDM`, you must make extra annotations to add enough context to the module:

. The `EntitySet` where the expansion takes place should have a `NavigationPropertyBinding` for every expandable `NavigationProperty` of its `Entity`. +
This is used to select which `<entity-collection-source/>` is executed when expanding that property.
. Each expandable `NavigationProperty` should have a `ReferentialConstraint` attached. +
This creates the inner query, where the value of `Property` is matched against the value of `ReferencedProperty`.

=== Flow Execution

. The main flow is executed and completed resulting in a collection of `entities`.
. The OData module gathers all the properties that need expansion.
. For each `NavigationProperty`:
.. Get the `source property` from its `ReferentialConstraint`.
.. Get the `referenced property` from its `ReferentialConstraint`.
.. Get the `destination entity set` from its `NavigationPropertyBinding`.
.. For each of the `entities` get the resolved `source property`. Add these values to a `source property list`.
.. Execute the `internal` request by invoking the `<entity-collection-source/>` for `destination entity set` with `$filter=referenced property` in `(...source property list)`.

=== Error Handling and Error Propagation

Error handling for OData v4 applications is local to each flow, whether you use `generic expansion` or not. Error handling code for a given `EntitySet` belongs to the flow implementations for that entity set, both for normal requests and for the internal requests observed during expansion processing.

Handling errors during the expansion process is not supported, because the expansion process runs after the execution of the flow finishes. There are two options available for handling errors:

- *Ignore errors during expansion:* Errors during generic expansion are ignored. +
By default, the expansion of collections and single objects are resolved to empty lists and `null` values respectively.
- *Propagate errors during expansion:* Errors arise during generic expansion. +
When an error reaches the OData v4 router, the original request is answered with an error response.

You can configure error handling *per-source* on the *Capabilities* tab.

=== Limitations

* Only the first `ReferentialConstraint` is considered. +
Navigation properties that use compound keys are not supported.
* Expansion is done `field-by-field` instead of `EntitySet-by-EntitySet`. +
This can cause more internal requests than necessary.
* The expanded entities always have an `<entity-collection-source/>` implementation. +
Expansion using `<entity-source/>` implementations are not executed due to performance concerns.

== Implementation Guidelines

To implement the `generic expansion` feature, you must annotate each source with the types that it can expand. Enabling `$expand` without restrictions enables API clients to write arbitrarily complex queries, which can create performance issues.

If you implement `$expand` manually for some relationships, leave these relationships out of the list on the *Expandable Navigation Properties* option. The navigation properties that don't use the `generic expansion` feature need manual implementations inside the flow.

=== Implementation Checklist

. Check that your CSDL file and Mule application meet the expected requirements:
** Every `NavigationProperty` has one `ReferentialConstraint`.
** Every `EntitySet` has one `NavigationPropertyBinding` for each `NavigationProperty` of its entity type.
** Every `<entity-collection-source/>` supports the `in` operator for the `$filter` system query option.
. For each source for which you want to enable `generic expand` support:
.. Open the *Capabilities* tab.
.. Edit inline the *Expandable navigation properties* field.
.. Add the name of each navigation property that you want to be expandable by using `generic expand`.
.. Depending on your use case, check *Ignore errors on expand* to avoid errors during the generic expansion and to generate errors on the main flow.
. Verify that your existing flows support the `$expand` feature.
