= Configuring the Response Headers and Status Code
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

Within the HTTP Listener configuration, you can customize the HTTP response body, headers, status code, and reason phrase.

== Configure Variable Names

The APIkit Router configuration has two properties that enable you to configure the variables that the HTTP listener searches for by default:

* `outboundHeadersMapName`: Name of the variable that contains a headers map added in the response (`outboundHeaders` by default)
+
* `httpStatusVarName`: Name of the variable that stores the status code to set in the response (`httpStatus` by default)

*APIkit Router* creates both variables and facilitates the inclusion of custom HTTP headers and status codes in the response.

// TODO Maybe an image of the Router configuration as well?

[source,xml,linenums]
----
<apikit:config  name="api-config"
                api="api.raml"
                outboundHeadersMapName="outboundHeaders"
                httpStatusVarName="httpStatus"/>
----

To modify the default names of these variables, it is crucial to update the default HTTP listener configuration to ensure alignment between the variable names and the configuration.

[source,xml,linenums]
----
<http:listener config-ref="api-httpListenerConfig" path="/api/*">
    <http:response
        statusCode="#[vars.httpStatus default 200]">
        <http:headers>#[vars.outboundHeaders default {}]</http:headers>
    </http:response>
    <http:error-response
        statusCode="#[vars.httpStatus default 500]">
        <http:body>#[payload]</http:body>
        <http:headers>#[vars.outboundHeaders default {}]</http:headers>
    </http:error-response>
</http:listener>
----

== Add a Header to a Response

Put the header you want to add inside the `outboundHeaders` map, as shown in the following example:

[source,xml,linenums]
----
<set-variable
    value='#[vars.outboundHeaders default {} ++ {newHeaderName: "Header value"}]'
    variableName="outboundHeaders"/>
----

== Set the Status Code of a Response

To assign a specific value to the `httpStatus` variable, you can use the following example as a reference:

[source,xml,linenums]
----
<set-variable
    value="201"
    variableName="httpStatus"/>
----

== See Also
// TODO Fix the reference to the HTTP listener
* https://docs.mulesoft.com/http-connector/1.7/http-listener-ref#sending-http-responses[Sending HTTP Responses when configuring HTTP listener source in Mule 4^]
