= APIkit Overview
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: overview-4.adoc

APIkit is a toolkit that simplifies the development of API-led applications for Mule developers. It scaffolds applications from a given specification, validates inputs parameter validation, and creates xref:munit::munit-scaffold-test-task.adoc[MUnit test suites]. APIkit has a module for each supported web-service type:

* xref:apikit-4-for-graphql.adoc[] supports GraphQL APIs. 
* xref:apikit-4-for-odatav2.adoc[] and xref:apikit-4-for-odatav4.adoc[] support OData APIs. 
* xref:apikit-4-for-rest.adoc[] supports RAML and OAS APIs.
* xref:apikit-4-for-soap.adoc[] supports SOAP APIs. 

With APIkit, incoming requests are intelligently routed to the appropriate endpoints based on the defined API contracts. This routing mechanism simplifies request handling, improves performance, and ensures that requests are processed by the correct API resources.

Although each module is designed for a family of web services, all modules share common usage patterns. So if you are a Mule developer that works with SOAP APIs, you can easily get used to working with GraphQL, RAML, OData, or OAS APIs.

== Features

* APIkit generates the structure of a Mule application based on a supported API specification.
* APIkit includes sources and operations that perform complex input validations according to the requirements described in the API specification.
* APIkit for REST module includes an API console that enables you to experiment with the API project as you develop it.
* Some APIkit modules include extensions for xref:studio::index.adoc[Anypoint Studio] and xref:anypoint-code-builder::index.adoc[Anypoint Code Builder] for enhancing your editing experience if you choose to use the supported development environments.

== Prerequisites

You need to have access to xref:studio::index.adoc[Anypoint Studio] or xref:anypoint-code-builder::index.adoc[Anypoint Code Builder] to scaffold a supported API specification with APIkit.

== APIkit Versions

APIkit is designed to work as a module with Mule runtime version 4. Documentation for the Mule 3 implementation of APIkit is available https://docs.mulesoft.com/apikit/3.x/[here]. If you use APIkit on Mule 3, the module version matches the runtime version.

By default, Studio includes APIkit for REST and APIkit for SOAP modules. If you need GraphQL or OData modules, follow the installation instructions in each section.

== See Also

* xref:apikit-compatibility.adoc[]
* xref:apikit-4-for-graphql.adoc[]
* xref:apikit-4-for-odatav2.adoc[]
* xref:apikit-4-for-odatav4.adoc[]
* xref:apikit-4-for-rest.adoc[]
* xref:apikit-4-for-soap.adoc[]
